const translations={en:{
"nav.home":"Home","nav.services":"Services","nav.work":"Work","nav.about":"About","nav.contact":"Contact",
"hero.eyebrow":"DIGITAL PRESENCE, BUILT RIGHT","hero.title":"We build a digital presence<br><em>your business deserves.</em>","hero.text":"Modern, fast and professional websites that help businesses show up with confidence and turn visitors into customers.","hero.cta":"Start a project","hero.work":"View our work",
"intro.label":"WHY SARONSOFT","intro.title":"Simple to use.<br>Strong to remember.","intro.text":"We focus on what businesses actually need: clear design, comfortable user experience, high performance and a consistent digital identity.","intro.more":"Discover SARONSOFT →",
"services.title":"Everything you need<br>for a stronger digital front.","services.more":"All services →","card.web":"Corporate websites","card.webText":"Professional websites that reflect your brand and build trust.","card.landing":"Landing pages","card.landingText":"Focused pages for campaigns, services and offers, designed around one clear goal.","card.ui":"UI / UX design","card.uiText":"Modern, comfortable interfaces that make every visitor journey clearer.",
"cta.title":"Ready to make your business<br>look different?","cta.button":"Let's talk","footer.tag":"Building a digital presence worthy of your business.","footer.explore":"Explore","footer.contact":"Contact","footer.rights":"All rights reserved.",
"servicesPage.title":"Digital services<br><em>built for business.</em>","servicesPage.text":"Practical, elegant web solutions — from idea to launch.","service1.title":"Corporate websites","service1.text":"Professional multi-page websites for your company, services, work and contact channels.","service2.title":"Landing Pages","service2.text":"Fast, focused pages for marketing campaigns, services and offers.","service3.title":"UI / UX","service3.text":"Consistent, comfortable interfaces for mobile and desktop, with attention to detail.","service4.title":"Web development","service4.text":"Turning designs into fast, responsive, organized websites ready to launch.",
"work.title":"Work that makes<br><em>a strong first impression.</em>","project1":"Professional company website","project2":"Digital identity for a brand","project3":"Service landing page",
"about.title":"We believe a good website<br><em>should be felt before it is explained.</em>","about.subtitle":"Calm design.<br>Clear results.","about.text1":"SARONSOFT specializes in building professional websites for companies and businesses. We avoid unnecessary complexity and focus on an experience that creates trust from the first moment.","about.text2":"Every page has a purpose, and every detail has a reason — from content structure to performance and responsive design.",
"contact.title":"Let's build<br><em>something beautiful.</em>","contact.text":"Send us a few details about your idea and we'll get back to you soon.","form.name":"Name","form.email":"Email","form.message":"How can we help?","form.send":"Send message"
},ar:{}};
document.querySelectorAll("[data-i18n]").forEach(el=>translations.ar[el.dataset.i18n]=el.innerHTML);
const btn=document.getElementById("langBtn");let lang=localStorage.getItem("saronsoft-lang")||"ar";
function setLang(l){lang=l;localStorage.setItem("saronsoft-lang",l);document.documentElement.lang=l;document.documentElement.dir=l==="ar"?"rtl":"ltr";document.querySelectorAll("[data-i18n]").forEach(el=>{const v=translations[l][el.dataset.i18n];if(v)el.innerHTML=v});if(btn)btn.textContent=l==="ar"?"EN":"AR"}
if(btn)btn.addEventListener("click",()=>setLang(lang==="ar"?"en":"ar"));setLang(lang);